### ISSUE TITLE
More compact Ammo Storage

### ISSUE THREAD

**Issue by TheQuaccer** [Alziibun/Perdition#19]
A way to store ammo in bigger crates but with a higher weight.
I made some recipes already for this in Perdition_UnusedCrateStacking.txt. The basic's is that you can store 300 rounds of ammo in a crate which then saves space but you can carry around 300 round in a box. the way to take em out is to take out 30 rounds each
Each time you craft you get 30 rounds and it uses 1/10 unit from the crate

This system is already in the scrap weapons mod for their ammo and i see its pretty neat.

**Comment by Alziibun** [comment]
A couple issues with the code you have as of writing:
- let's not use recipes for this, we can use a context menu action to dynamically remove ammo

### Todo
- [ ] have the transferral time scale off reloading
- [x] fix tooltips as stated in #22
- [ ] create a model and icon for each, or recycle them
- [ ] create context menu action for ammo transferral
